dependencies:
  - smartcontractkit/chainlink@2.18.0

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@2.18.0"

networks:
  sepolia:
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306" 
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: True
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: True